name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-manager:
    uses: ./.github/workflows/build-manager.yml
    secrets: inherit
  release:
    needs:
      - build-manager
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5
      - name: Rename ksud
        run: |
          mkdir -p ksud
          for dir in ./ksud-*; do
              if [ -d "$dir" ]; then
                 echo "----- Rename $dir -----"
                 ksud_platform_name=$(basename "$dir")
                 find "$dir" -type f -name "ksud" -path "*/release/*" | while read -r ksud_file; do
                   if [ -f "$ksud_file" ]; then
                     mv "$ksud_file" "ksud/$ksud_platform_name"
                   fi
                 done
              fi
          done
          
      - name: Display structure of downloaded files
        run: ls -R

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            manager/*.apk
            ksud/ksud-*
